name: Security Check

on:
  push:
    branches:
      - main

jobs:
  snyk:
    name: Snyk Vulnerability Scan
    runs-on: ubuntu-latest
    env:
      SNYK_CLI_VERSION: 1.1305.2
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '24'

      - name: Install dependencies
        run: npm ci

      - name: Install Snyk CLI
        run: npm install --global snyk@"$SNYK_CLI_VERSION"

      - name: Run Snyk checks
        run: snyk test --file=package.json --severity-threshold=high
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
